[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://help-together-backend-1.onrender.com/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
